appName: gitops-platform

replicaCount: 3

image:
  repository: ghcr.io/mohassan521/gitops-platform
  tag: f5aec18759335d699602fc5927f42ff20edd9cd3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: 62.238.34.238.sslip.io