replicaCount: 3

image:
  repository: ghcr.io/mohassan521/gitops-platform
  tag: 103eddde8a023e06440a42bf97adf64c5258e875
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: 62.238.34.238.sslip.io