replicaCount: 3

image:
  repository: ghcr.io/mohassan521/gitops-platform
  tag: 2c7d5dffaded884274e2f3ebaf94fc91b636ccd9
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: 62.238.34.238.sslip.io