apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-platform

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: gitops-platform

  template:
    metadata:
      labels:
        app: gitops-platform
  
    spec:
      containers:
        - name: gitops-platform
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 3000