{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: gitops-platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-pod
    # kubernetes.io/ingress.class: traefik

spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: gitops-platform-tls

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitops-platform
                port:
                  number: {{ .Values.service.port }}

{{- end }}