apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: gitops-platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL: 'https://github.com/mohassan521/gitops-platform.git'
    targetRevision: main
    path: helm

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitops-platform
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true